### ISSUE TITLE
How to list unspet transactions of an address?

### ISSUE THREAD

**Issue by cevin** [Bit-Wasp/bitcoin-p2p-php#29]

**Comment by afk11** [comment]
You can't look up tx's by an address over the p2p network. Why are you trying to do it this way? 

Unless you have a full node, you're using an API belonging to _someone_. Electrum uses publicly accessible servers that support querying for such data. They offer SPV level security, though comes at a privacy cost for sure. 

Since you don't want to build around bitcoind, where do you expect to get this data? You'll either need to write your own full node (certainly worse than using bitcoind), or drop down to SPV. It's a massive drop between the two, so I need to know which you're prepared to accept before advising what you should be using.

**Comment by afk11** [comment]
Feel free to catch me on Gitter: https://gitter.im/Bit-Wasp/bitcoin-php

**Comment by cevin** [comment]
@afk11 

I know I must need synced all blocks and transactions data, I running 3 bitcoind servers trying to use a Python script to syncing all rawtransaction data.  But in china, have not  more information about this. - -#

So, The question maybe is this, In syncing process, how to only record all unspent transactions data and the address to my database.

like the first need use getblock to get all transactions of every block

**Comment by afk11** [comment]
Yeah.. that in itself takes quite a while.. Though, at least bitcoin-php has something that makes only two RPC requests per block :) 

So, since you're writing a wallet, you'll have a list of public keys, and their addresses. 

Addresses don't really exist on the network, they are only for humans. But, inside an address is a public-key-hash. Bitcoin Core and other clients know when they you paying to an address, the hash is to be taken, and the output script constructed. 

See https://en.bitcoin.it/wiki/Script - way down the bottom you'll have a description of the types. 

What you COULD do, is for every output, see if the binary matches: script[0] = 'OP_DUP', script[1] = 'OP_HASH160', script[2] instanceof buffer && script[2]->getSize() == 20, .................and so on. They don't be written as OP_DUP, but instead, as binary digits. Just work around the encoding. 

You can use an OutputClassifier for this (bitcoin-php), or just hardcode the opcode constants, and use fixed string offsets to check the output script for a transaction type your wallet supports. 

There will be many pay-to-pubkey-hash outputs, but only some will include the hash of YOUR public keys. 

You will end up with a loop for every transaction in a block: 
(i) Every time you find an output paying you, save that record to the database [txid, vout, scriptPubKey, value]. 

(ii) At the same time, every transaction that isn't coinbase, spends old transaction outputs. You could just query your DB for all hash/vout's that involve your wallet. If they are being spent, mark them unspendable. 

Note - this can be risky, because of very short lived forks. Be aware of it, you'll have to code around this later (ie, transactions can be undone if the block is orphaned) 

It can be optimized from here, but that would be the easiest way. Don't track every single output in the blockchain, just those that are involve you, and mark them spent when you're done. That way you can query `SELECT * FROM utxos WHERE spent IS FALSE`

**Comment by cevin** [comment]
So,

1.use `getblock` get all transactions for every block ( from 0 - latest )

2.use `getrawtransaction` get `output & input `, loop all `outputs & inputs ` and check the database if exists mark it is spent if not exists insert to database and mark it is unspent (maybe I can to update the confirmed number)

3.when use wif key to make a transaction, `SELECT * FROM txs WHERE address = :address and spent = 0` ?

But, How to confirm current transaction's output  exists in database and is a old input ? @.@

**Comment by afk11** [comment]
That's pretty much correct. BitcoinPHP has a class Bitcoind, which decorates some of the getblock / related calls. If you call getblock, you get a BlockInterface. From there you can do Block::getTransactions(). Each Transaction has getInputs(), or getInput($x), and the same for outputs. 

It's best to do decoding in your code, not over the RPC, otherwise you make several calls per transaction.

You'll have to be specific, what are you trying to test for?

**Comment by cevin** [comment]
to build a simple online wallet and public api to make transaction and boradcast to network :)
like https://blockchain.info/

Bake issue. the code like this ?

```
$rpc = \JsonRpc::Factory($config);
$txdb = \Database::Factory($config);

$count = $rpc->getblockcount();

for ($i=0;$i<=$count;$i++) {
    $hash = $rpc->gethash($rpc->getblockhash($i));
    foreach ($hash['tx'] as $tx) {
        $raw = $rpc->getrawtransaction($tx);
        if (isset($raw['vin'][0]['coinbase'])) {
            foreach ($raw['vout'] as $out) {
                $txdb->insert('tx',[
                    'txid'=>$raw['txid'],
                    'value'=>$out['value'],
                    'n' =>$out['n'],
                    'pubkey' => $out['scriptPubKey']['hex'],
                    'spent' => 0
                ]);
            }
        } else {
            foreach ($raw['vin'] as $in) {
                $oldtx = $db->getTx($in['txid']);
                if ($oldtx) {
                    $oldtx->spent = 1;
                    $oldtx->save();
                } else {
                    $db->insert('tx',[
                        'txid'=>$in['txid'],
                        'value'=>$in['value'],
                        'n' => $in['n'],
                        'pubkey'=> ? ,// the simple rawtransaction is from blockexplorer.com 
                        'spend'=>0
                    ]);
                }
            }
        }
    }
}
```

**Comment by afk11** [comment]
Ah - damn, probably you need txindex=1 set for that. Oops. 

The scriptPubKey doesn't show much, but it does change. The first three and last two bytes don't change for the usual script type. Inside, however, is the pubkey hash, which changes.

There are some small errors. First, you insert the outputs, not inputs. (They're inputs when you spent them) Coinbase, you're correct you wouldn't mark these as spent, but again, it's just the outputs you'd want to store. 

`
foreach ($tx['vin'] as $nIn => $input) {
    if (!isset($tx['coinbase'])) {
      if (check_affects_my_wallet($input)) {
        $db->update('tx', $id, ['spent' => 1]);
      }
    }
}

foreach ($tx['vout'] as $nout => $out) {
   if (check_belongs_to_me($out)) {
    $db->insert('tx', [
       'txid'=>$tx['hash'],
       'value'=>$in['value'],
       'n' => $nout,
       'pubkey'=> ? ,// the simple rawtransaction is from blockexplorer.com 
       'spend'=>0    
   ]);
  }
}`

Quick FYI - batch insert/update as much as you can, and only save the outputs that _pay to you_, so won't have to 2000 transaction every block as 'spent'.

**Comment by cevin** [comment]
So, the `txid` is always not change? like I send `0.1BTC` to an address, when target address have a transaction, in make transaction process in the `inputs array` the `txid` is my send to another people address's `txid` ? and when the bitcoind synced this block and transaction array, decode and loop it, update the database! okay,  I seem to understand.

But in the looping how to get current from address or target address of transaction ? @.@

**Comment by afk11** [comment]
The inputs array should have the same txid / n as the output that paid to you.. 

(Most) scriptPubKeys contain a hash, the same that's used in address. 

Bitcoind vout[n]['scriptPubKey']['addresses'] will usually always have one address; the situation where there would be several doesn't really happen anymore. 

You should spend some time studying what addresses are used for - there are two different types that are used quite differently! It's helpful to see the difference I think. A big hint is the hash160 is the hash that's inside the address.

I'd prefer to let you work the rest out. It sounds like you're doing well, but it's no longer an issue for these libraries. For a lot of useful info, I'd suggest these pages: https://en.bitcoin.it/wiki/Script (especially the bottom), https://en.bitcoin.it/wiki/Transactions, https://en.bitcoin.it/wiki/Protocol_documentation

**Comment by cevin** [comment]
```php
$db = new PDO('pgsql:dbname=explore;host=localhost;','pgsql','');
$count = $rpc->getblockcount();
for ($i=0;$i<=$count;$i++) {

    $hash = $rpc->getblock($rpc->getblockhash($i));
    foreach ($hash['tx'] as $tx) {
        $raw = $rpc->getrawtransaction($tx);
        if ($raw == -5) {
            continue;
        } else {
            $x = $rpc->decoderawtransaction($raw);
            if(is_array($x)) {
                foreach ($x['vin'] as $vin) {
                    if (isset($vin['coinbase']))
                        continue;
                    $txid = $vin['txid'];
                    $stmt = $db->prepare('delete from tx where txid = :id');
                    $stmt->bindValue('id',$x['txid']);
                    $stmt->execute();
                }
                foreach ($x['vout'] as $index=>$out) {var_dump($out['value']);
                    $stmt = $db->prepare('insert into tx (txid,"value",n,pubkey,address) values (:id,:value,:n,:pubkey,:address)');
                    $stmt->bindValue(':id',$x['txid']);
                    $stmt->bindValue(':value',$out['value']);
                    $stmt->bindValue(':n',$index);
                    $stmt->bindValue(':pubkey',$out['scriptPubKey']['hex']);
                    $stmt->bindValue(':address',$out['scriptPubKey']['addresses'][0]);
                    $stmt->execute();
                }
            }
        }
    }
}

// Make raw transaction
$address_unspents_stmt = $db->prepare('select * from tx where address = :address');
$address_unspents_stmt->bind(':address',$address);
$address_unspents_stmt->execute();
$unspents = $address_unspents_stmt->fetchAll(2);

$inputs = [];
foreach ($unspents as $unspent) {
    $input = [
        'txid'=>$unspent['txid'],
        'vout'=>$unspent['n'],
        'scriptPubKey' => $unspent
    ];
    array_push($inputs, $input);
}
```

**Comment by afk11** [comment]
That looks pretty good. Remember what I said about batch inserts/updates. Also, if you're just writing a wallet you should check if the detected scriptPubKey matches one belonging to your addresses.

**Comment by cevin** [comment]
@afk11 
very very thanks.

please do not close this issue.

**Comment by cevin** [comment]
How to get every transaction confirmations?

What time to update the transaction confirmations?

**Comment by afk11** [comment]
As I said, this is no longer an issue for this library. You'll have to work it out for yourself :-)

**Comment by cevin** [comment]
@afk11 
I know. 

But the time , how to get transaction confirmations? - -# I don't know .

Please tell me. Use google do not found any thing for me.

**Comment by afk11** [comment]
Closing, as not relevant to this library.
